language: node_js
  -2.6.6
  cache: yarn
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
 on:
  branch: master
  
